### ISSUE TITLE
Bug on Starter v2

### ISSUE THREAD

**Issue by TurboProgramming** [Makeroid/Starter#1]
Why is this hapenning?

![capture](https://user-images.githubusercontent.com/17576065/33230579-3f8b6388-d1f7-11e7-81e6-d228d3a93f83.PNG)

**Comment by pavi2410** [comment]
Is it Windows 10 64-bit?

**Comment by TurboProgramming** [comment]
Yes

**Comment by pavi2410** [comment]
And is it occurred during installation or after running the app?

**Comment by TurboProgramming** [comment]
after running the app.

**Comment by TurboProgramming** [comment]
I also tried installing v1. Also, tried installing and uninstalling v2 5 times. It won't solve the problem.

**Comment by pavi2410** [comment]
You will need to install this: https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by TurboProgramming** [comment]
The link you provided is not valid.

**Comment by TurboProgramming** [comment]
OK it worked. Sorry.

**Comment by TurboProgramming** [comment]
I'm currently not at home right now, so when I go home, I will definitely try it out and let you know.

**Comment by barreeeiroo** [comment]
We have released a new version for 32bits devices, made by Ravi at the community
Should be fixed now
